### PR TITLE
Make control add class to converted element instead of passed in element

### LINKED ISSUE #62: Creating an instance of a named control by passing a selector throws
If you provide a `name` when extending a control and then create an instance of it by passing a selector, it will throw when trying to [add a className to the element](https://github.com/canjs/can-control/blob/master/can-control.js#L291).

Here is an example that causes the error:
```
var MyControl = can.Control.extend('MyControl');
new MyControl('#mycontrol');
```
and the error:

```
Uncaught TypeError: Cannot read property 'match' of undefined
    at has (http://localhost/nokia-npm/node_modules/can-util/dom/class-name/class-name.js:9:26)
    at add (http://localhost/nokia-npm/node_modules/can-util/dom/class-name/class-name.js:62:17)
    at EPIC_TooltipController.setup (http://localhost/nokia-npm/node_modules/can-control/can-control.js:293:31)
    at Function.newInstance (http://localhost/nokia-npm/node_modules/can-construct/can-construct.js:288:22)
```

### PR DESCRIPTION
**Pull request by ccummings**
Closes #62

### CODE REVIEW

File: can-control_test.js [hunk 1]
```diff
@@ -480,6 +480,16 @@ test("Creating an instance of a named control without passing an element", funct
...
 });
 
+test("Creating an instance of a named control passing a selector", function() {
+
+	this.fixture.appendChild( fragment('<div id=\'my-control\'>d</div>') );
+	
+	var MyControl = Control.extend('MyControl');
+	var myControlInstance = new MyControl('#my-control');
+
+	ok(myControlInstance.element.className === 'MyControl', "Element has the correct class name");
```
Comment (phillipskevin) [inline can-control_test.js]: In IE9, the `className` gets set as `" MyControl"`, so you should use `className.has.call(myControlInstance.element, 'MyControl')`.

**Comment by phillipskevin** [comment]
Also, can you rebase with master?
